#!/usr/bin/env node

require('dotenv/config')
const debug = require('debug')('pinboard-updater')

const fetch = require('node-fetch')
const convert = require('xml-js')
const { map, filter } = require('lodash')
const { loadFromString } = require('html-metadata')
const compareAsc = require('date-fns/compareAsc')
const queryString = require('query-string')
const { Logger } = require('tslog')

const { PINBOARD_API_KEY, PINBOARD_LAST_DATE, LOG_LEVEL } = process.env

const log = new Logger({ minLevel: LOG_LEVEL || 'info' })

debug('PINBOARD_API_KEY', PINBOARD_API_KEY)
debug('PINBOARD_LAST_DATE', PINBOARD_LAST_DATE)

async function getBookmarks () {
  const response = await fetch(`https://api.pinboard.in/v1/posts/all?auth_token=${PINBOARD_API_KEY}`)
  const responseText = await response.text()
  const responseXmlObject = convert.xml2js(responseText, { compact: true })
  const posts = responseXmlObject.posts.post

  return map(posts, '_attributes')
}

async function scrapeBookmark (bookmark) {
  const response = await fetch(bookmark.href)
  const html = await response.text()

  const metadata = await loadFromString(html)

  return {
    ...bookmark,
    description: metadata.general.title,
    extended: metadata.general.description,
  }
}

async function updateBookmark (bookmark) {
  const qs = queryString.stringify(
    {
      auth_token: PINBOARD_API_KEY,
      url: bookmark.href,
      description: bookmark.description,
      extended: bookmark.extended,
      tags: bookmark.tag,
      dt: bookmark.time,
      replace: 'yes',
      toread: bookmark.toread
    },
    {
      skipNull: true,
      skipEmptyString: true,
    }
  )

  await fetch(`https://api.pinboard.in/v1/posts/add?${qs}`)
}

function filterBookmarksAfterDate (bookmarks, date) {
  return filter(bookmarks, (bookmark) => compareAsc(new Date(bookmark.time), date) >= 0)
}

async function main () {
  const bookmarks = filterBookmarksAfterDate(
    await getBookmarks(),
    new Date(PINBOARD_LAST_DATE || 0)
  )

  debug('bookmarks to update', bookmarks.length)

  let bookmark

  for (bookmark of bookmarks) {
    try {
      try {
        debug('scraping bookmark', bookmark.href)
        bookmark = await scrapeBookmark(bookmark)
      } catch (e) {
        log.error('Error while scraping bookmark', bookmark.href, e)
        throw e
      }

      try {
        debug('updating bookmark', bookmark.href)
        await updateBookmark(bookmark)
      } catch (e) {
        log.error('Error while updating bookmark', bookmark.href, e)
        throw e
      }

      await new Promise((resolve) => setTimeout(resolve, 100))
    } catch (e) {
      // noop
    }
  }
}

(async function() {
  await main()
}());
